codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"  # 現在のカバレッジ(54.85%)に合わせて調整
  
  status:
    project:
      default:
        target: auto
        threshold: 2%  # 閾値を少し緩和
        # PRタイプによって異なる挙動を設定
        if_not_found: success
        if_ci_failed: success
        informational: false  # ステータスチェックとして表示
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 1%
        # PRタイプによって異なる挙動を設定
        if_not_found: success
        if_ci_failed: success
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "backend/tests/**/*"
  - "backend/src/bin/**/*"
  - "backend/src/main.rs"  # エントリーポイント
  - "frontend/**/*"
  - "terraform/**/*"
  - "airflow/**/*"
  # データベース接続関連（統合テストで確認）
  - "backend/src/db/connection.rs"
  # マイグレーション関連
  - "**/migrations/**/*"