# Clippy設定
msrv = "1.70.0"

# 警告レベルの調整
warn = [
    "clippy::all",
    "clippy::pedantic",
    "clippy::nursery",
]

# 特定の警告を無効化
allow = [
    "clippy::module_name_repetitions",
    "clippy::must_use_candidate",
]