version: '3.8'

services:
  test-db:
    image: postgres:16-alpine
    container_name: iso-flow-test-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_iso_flow
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_iso_flow"]
      interval: 5s
      timeout: 5s
      retries: 5