-- TIMESTAMPカラムをTIMESTAMPTZに変更
ALTER TABLE trade_news 
    ALTER COLUMN published_at TYPE TIMESTAMPTZ,
    ALTER COLUMN scraped_at TYPE TIMESTAMPTZ,
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ;